category: media-sound
conflicts:
  category: app-admin
  id: 0
  name: helm
  version: ""
description: Open source polyphonic software synthesizer with lots of modulation
id: 0
license: GPL-3+
name: helm
requires:
  category: media-libs
  id: 0
  name: freetype
  version: ""
  category: media-libs
  id: 0
  name: lv2
  version: ""
  category: virtual
  id: 0
  name: jack
  version: ""
  category: x11-libs
  id: 0
  name: libXcursor
  version: ""
  category: x11-libs
  id: 0
  name: libXinerama
  version: ""
  category: media-libs
  id: 0
  name: alsa-lib
  version: ""
  category: virtual
  id: 0
  name: opengl
  version: ""
  category: x11-libs
  id: 0
  name: libX11
  version: ""
  category: x11-libs
  id: 0
  name: libXext
  version: ""
  category: x11-libs
  id: 0
  name: libXrandr
  version: ""
uri:
- https://github.com/mtytel/helm/archive/v0.9.0.tar.gz -> helm-0.9.0.tar.gz
use_flags:
- ""
version: 0.9.0-r1
