category: media-sound
conflicts:
- 
  category: app-admin
  description: ""
  license: ""
  name: helm
  
  version: ""
description: Open source polyphonic software synthesizer with lots of modulation
license: GPL-3+
name: helm
requires:
- 
  category: media-libs
  description: ""
  license: ""
  name: alsa-lib
  
  version: ""
- 
  category: media-libs
  description: ""
  license: ""
  name: freetype
  
  version: ""
- 
  category: media-libs
  description: ""
  license: ""
  name: lv2
  
  version: ""
- 
  category: x11-libs
  description: ""
  license: ""
  name: libXext
  
  version: ""
- 
  category: x11-libs
  description: ""
  license: ""
  name: libXinerama
  
  version: ""
- 
  category: x11-libs
  description: ""
  license: ""
  name: libXrandr
  
  version: ""
- 
  category: virtual
  description: ""
  license: ""
  name: jack
  
  version: ""
- 
  category: virtual
  description: ""
  license: ""
  name: opengl
  
  version: ""
- 
  category: x11-libs
  description: ""
  license: ""
  name: libX11
  
  version: ""
- 
  category: x11-libs
  description: ""
  license: ""
  name: libXcursor
  
  version: ""
uri:
- https://github.com/mtytel/helm/archive/v0.9.0.tar.gz -> helm-0.9.0.tar.gz
use_flags:
- ""
version: 0.9.0-r1
