category: app-emacs
conflicts: []
description: Emacs incremental completion and selection narrowing framework
id: 0
license: GPL-3+
name: helm
requires:
- 
  category: app-emacs
  description: ""
  id: 0
  license: ""
  name: popup
  
  version: ""
- 
  category: app-emacs
  description: ""
  id: 0
  license: ""
  name: async
  
  version: ""
uri:
- https://github.com/emacs-helm/helm/archive/v3.6.0.tar.gz -> helm-3.6.0.tar.gz
version: 3.6.0
