category: app-admin
conflicts: []
description: Model-driven deployment, config management, and command execution framework
id: 0
license: GPL-3
name: ansible
requires:
  category: dev-python
  id: 0
  name: jinja
  version: ""
  category: dev-python
  id: 0
  name: pyyaml
  version: ""
  category: dev-python
  id: 0
  name: setuptools
  version: ""
  category: dev-python
  id: 0
  name: six
  version: ""
  category: dev-python
  id: 0
  name: netaddr
  version: ""
  category: virtual
  id: 0
  name: ssh
  version: ""
  category: dev-python
  id: 0
  name: paramiko
  version: ""
  category: dev-python
  id: 0
  name: cryptography
  version: ""
  category: dev-python
  id: 0
  name: httplib2
  version: ""
  category: dev-python
  id: 0
  name: pexpect
  version: ""
  category: net-misc
  id: 0
  name: sshpass
  version: ""
use_flags:
- doc
- test
version: "9999"
