category: app-metrics
conflicts:
- 
  category: app-metrics
  description: ""
  id: 0
  license: ""
  name: prometheus
  
  version: ""
description: prometheus monitoring system and time series database
id: 0
license: Apache-2.0
name: prometheus-bin
requires:
- 
  category: acct-group
  description: ""
  id: 0
  license: ""
  name: prometheus
  
  version: ""
- 
  category: acct-user
  description: ""
  id: 0
  license: ""
  name: prometheus
  
  version: ""
uri:
- https://github.com/prometheus/prometheus/releases/download/v2.15.2/prometheus-2.15.2.linux-amd64.tar.gz
version: 2.15.2
