category: app-admin
description: Kubernetes Package Manager
id: 0
license: Apache-2.0
name: helm
uri:
- https://github.com/helm/helm/archive/v3.0.0.tar.gz -> helm-3.0.0.tar.gz
use_flags:
- ""
version: 3.0.0
