category: dev-python
conflicts: []
description: Provides HTTP request metrics to export into Prometheus
id: 0
license: MIT
name: prometheus_flask_exporter
requires:
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: prometheus_client
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: flask
  
  version: ""
uri:
- https://github.com/rycus86/prometheus_flask_exporter/archive/0.5.1.tar.gz -> prometheus_flask_exporter-0.5.1.tar.gz
use_flags:
- test
version: 0.5.1
