category: app-emulation
conflicts: []
description: Cloud instance initialisation magic
id: 0
license: GPL-3
name: cloud-init
requires:
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: requests
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: jsonpatch
  
  version: ""
- 
  category: net-analyzer
  description: ""
  id: 0
  license: ""
  name: macchanger
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: oauthlib
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: pyserial
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: pyyaml
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: six
  
  version: ""
- 
  category: sys-apps
  description: ""
  id: 0
  license: ""
  name: iproute2
  
  version: ""
- 
  category: sys-fs
  description: ""
  id: 0
  license: ""
  name: growpart
  
  version: ""
- 
  category: virtual
  description: ""
  id: 0
  license: ""
  name: logger
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: jinja
  
  version: ""
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: configobj
  
  version: 5.0.2
- 
  category: dev-python
  description: ""
  id: 0
  license: ""
  name: jsonschema
  
  version: ""
uri:
- https://launchpad.net/cloud-init/trunk/18.5/+download/cloud-init-18.5.tar.gz
use_flags:
- test
version: "18.5"
