category: app-emacs
conflicts: []
description: Emacs incremental completion and selection narrowing framework
id: 0
license: GPL-3+
name: helm
requires:
  
  category: app-emacs
  id: 0
  name: popup
  
  version: ""
  
  category: app-emacs
  id: 0
  name: async
  
  version: ""
uri:
- https://github.com/emacs-helm/helm/archive/v3.2.tar.gz -> helm-3.2.tar.gz
version: "3.2"
