category: app-metrics
conflicts: []
description: Library that exports Nginx metrics to Prometheus
license: MIT
name: nginx-lua-prometheus
requires:
- 
  category: www-servers
  description: ""
  license: ""
  name: nginx[nginx_modules_http_lua]
  
  version: ""
- 
  category: dev-lang
  description: ""
  license: ""
  name: lua
  
  version: "5.1"
uri:
- https://github.com/knyar/nginx-lua-prometheus/archive/0.1-20170610.tar.gz -> nginx-lua-prometheus-0.1.tar.gz
version: 0.1_pre20170610
