category: x11-plugins
conflicts: []
description: Openbox app which acts as a system tray for KDE and GNOME2
id: 0
license: GPL-2
name: docker
requires:
  category: x11-libs
  id: 0
  name: libX11
  version: ""
  category: dev-libs
  id: 0
  name: glib
  version: 2.0.4
uri:
- https://icculus.org/openbox/2/docker/docker-1.5.tar.gz
use_flags:
- ""
version: 1.5-r2
