category: app-emulation
conflicts: []
description: The core functions you need to create Docker images and run Docker containers
license: Apache-2.0
name: docker
requires:
- 
  category: sys-fs
  description: ""
  license: ""
  name: lvm2
  
  version: 2.02.89
- 
  category: sys-libs
  description: ""
  license: ""
  name: libapparmor
  
  version: ""
- 
  category: net-firewall
  description: ""
  license: ""
  name: iptables
  
  version: "1.4"
- 
  category: sys-process
  description: ""
  license: ""
  name: procps
  
  version: ""
- 
  category: app-arch
  description: ""
  license: ""
  name: xz-utils
  
  version: "4.9"
- 
  category: dev-db
  description: ""
  license: ""
  name: sqlite
  
  version: 3.7.9
- 
  category: dev-vcs
  description: ""
  license: ""
  name: git
  
  version: "1.7"
- 
  category: dev-libs
  description: ""
  license: ""
  name: libltdl
  
  version: ""
- 
  category: app-emulation
  description: ""
  license: ""
  name: containerd
  
  version: 1.2.6
- 
  category: app-emulation
  description: ""
  license: ""
  name: docker-proxy
  
  version: 0.8.0_p20190513
- 
  category: sys-process
  description: ""
  license: ""
  name: tini
  
  version: 0.18.0
- 
  category: sys-libs
  description: ""
  license: ""
  name: libseccomp
  
  version: 2.2.1
uri:
- https://github.com/docker/docker-ce/archive/v18.09.9.tar.gz -> docker-18.09.9.tar.gz
use_flags:
- apparmor
- aufs
- btrfs
- +container-init
- device-mapper
- hardened
- +overlay
- seccomp
version: 18.09.9
