category: app-emulation
conflicts: []
description: Cloud instance initialisation magic
license: GPL-3
name: cloud-init
requires:
- 
  category: sys-apps
  description: ""
  license: ""
  name: iproute2
  
  version: ""
- 
  category: virtual
  description: ""
  license: ""
  name: logger
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: pyserial
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: configobj
  
  version: 5.0.2
- 
  category: dev-python
  description: ""
  license: ""
  name: requests
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: jsonpatch
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: six
  
  version: ""
- 
  category: net-analyzer
  description: ""
  license: ""
  name: macchanger
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: jinja
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: oauthlib
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: pyyaml
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: jsonschema
  
  version: ""
- 
  category: sys-fs
  description: ""
  license: ""
  name: growpart
  
  version: ""
uri: []
use_flags:
- test
version: "9999"
