category: app-admin
conflicts: []
description: Model-driven deployment, config management, and command execution framework
license: GPL-3
name: ansible
requires:
- 
  category: dev-python
  description: ""
  license: ""
  name: paramiko
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: pyyaml
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: setuptools
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: httplib2
  
  version: ""
- 
  category: virtual
  description: ""
  license: ""
  name: ssh
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: jinja
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: cryptography
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: six
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: netaddr
  
  version: ""
- 
  category: dev-python
  description: ""
  license: ""
  name: pexpect
  
  version: ""
- 
  category: net-misc
  description: ""
  license: ""
  name: sshpass
  
  version: ""
uri:
- https://releases.ansible.com/ansible/ansible-2.8.7.tar.gz
use_flags:
- doc
- test
version: 2.8.7
